export const INDUSTRY_CATEGORIES = [
    'Jasa',
    'F&B - Resto/depot',
    'Hotel & Villa',
    'Kesenian, hiburan dan rekreasi',
    'Perdagangan besar/eceran',
    'Konsultan',
    'Informasi & Komunikasi',
    'Kesehatan',
    'Event organizer',
    'Konstruksi - interior',
    'F&B - Coffee Shop',
    'Konstruksi - exterior',
    'Pendidikan',
    'Arsitektur',
    'Agen perjalanan',
    'Real estate',
    'F&B - Supplier',
    'Keuangan & Akuntansi',
    'F&B - Baking',
    'Elektronik',
    'Penyewaan & sewa guna',
    'Asuransi, dan lain lain',
    'Elektrikal',
    'Otomotif - Roda Empat',
    'Sosial',
    'Otomotif-Parts & aksesoris',
    'Ketenagakerjaan',
    'Trader Forex/saham',
    'Percetakan',
    'Otomotif-Roda Dua & Tiga',
    'Pemerintahan',
    'Pergudangan',
    'Perpajakan',
    'Valuta Asing',
    'Perikanan',
    'Pertanian',
    'Salon',
    'Sekuritas',
    'Ahli ilmiah & teknis',
    'Farmasi',
    'Gas & uap',
    'Pengolahan',
    'Badan internasional',
    'Kehutanan',
    'Pengangkutan',
    'Pertambangan & penggalian',
    'Reparasi',
];

export const HOBBY_LIST = [
    'Nonton film',
    'Ngopi',
    'Mendengar Musik',
    'Bulutangkis',
    'Seminar Bisnis',
    'Art & Craft',
    'Camping/glamping',
    'Running/jogging',
    'Fitness/weightlifting',
    'BBQ',
    'Persekutuan Doa',
    'Motorcycle Riding',
    'Nyanyi',
    'Pekerjaan Sosial',
    'Bermain Musik',
    'Memasak',
    'Baking',
    'Hiking',
    'Membaca',
    'Photography',
    'Yoga',
    'Gadget/elektronik',
    'Basketball',
    'Sepeda',
    'Meditasi',
    'Graphic Design',
    'Parenting',
    'Bertaman',
    'Gaming',
    'Billiard',
    'Melukis',
    'Soccer/futsal',
    'Merangkai Bunga',
    'Pilates',
    'Tennis meja',
    'Wine tasting',
    'Dancing',
    'Tennis',
    'Makeup/cosmetic',
    'Rafting',
    'Golf',
    'Catur',
    'Martial Art',
    'Memancing',
    'Nutrisi',
    'Horse Riding',
    'Scuba Diving',
    'Ice Skating',
    'Hair Styling',
    'Surfing',
    'Ikan hias',
    'Menjahit',
    'Kaligrafi',
    'Kayaking',
    'Origami',
    'Reptil',
];
