export const INDUSTRY_CATEGORIES = [
    'Jasa',
    'F&B - Resto/depot',
    'Hotel & Villa',
    'Retail',
    'Kuliner UMKM',
    'Kontraktor',
    'Interior Design',
    'Property Agent',
    'Arsitek',
    'Supplier Bahan Bangunan',
    'Pet Care',
    'Dokter Hewan',
    'Pet Shop',
    'Florist & Nursery',
    'Handcraft & Aksesoris',
    'Percetakan & Digital Printing',
    'Konveksi',
    'Fashion Designer',
    'Tekstil & Garmen',
    'Butik & Tailor',
    'Cuci Sepatu & Helm',
    'Laundry',
    'Make Up Artist',
    'Salon & Barbershop',
    'Spa & Massage',
    'Skincare & Klinik Kecantikan',
    'Optik & Kacamata',
    'Apotek',
    'Dokter & Klinik Medis',
    'Terapi & Fisioterapi',
    'Olahraga & Kebugaran',
    'Sanggar Seni & Musik',
    'Kursus & Bimbingan Belajar',
    'Daycare & Playgroup',
    'Rental Mobil & Motor',
    'Travel & Tour Organizer',
    'Event Organizer & Party Planner',
    'Sound System & Lighting',
    'Fotografer & Videografer',
    'Ekspedisi & Kurir Lokal',
    'Car Wash & Auto Detailing',
    'Aksesoris & Modifikasi',
    'Bengkel Mobil',
    'Bengkel Motor',
    'Mainan & Hobi',
    'Reparasi',
];

export const HOBBY_LIST = [
    'Nonton film',
    'Ngopi',
    'Kulineran',
    'Baca buku',
    'Menulis',
    'Main game (video game/board game)',
    'Menggambar/melukis',
    'Merajut/kerajinan tangan (crafting)',
    'Fotografi',
    'Berkebun/tanaman hias',
    'Memasak/baking',
    'Mendengarkan musik',
    'Mengoleksi barang (action figure, kaset, dll)',
    'Travelling/jalan-jalan',
    'Bersepeda',
    'Lari/jogging',
    'Berenang',
    'Sepak bola/futsal',
    'Basket',
    'Bulu tangkis',
    'Tenis meja/pingpong',
    'Tenis lapangan',
    'Golf',
    'Memancing',
    'Naik gunung/hiking',
    'Camping',
    'Otomotif (modifikasi/touring)',
    'Menari/dance',
    'Menyanyi/karaoke',
    'Main alat musik (gitar, piano, drum, dll)',
    'Belajar bahasa asing',
    'Membuat konten (vlog, TikTok, blog)',
    'Desain grafis/editing video',
    'Coding/programming',
    'Merawat hewan peliharaan',
    'Yoga/pilates',
    'Workout/gym',
    'Beladiri (karate, taekwondo, silat, dll)',
    'Skateboard/sepatu roda',
    'Panahan',
    'Menembak',
    'Bowling',
    'Biliar',
    'Catur',
    'Mengikuti tren fashion/styling',
    'Make up/beauty enthusiast',
    'Volunteer/kegiatan sosial',
    'Menjelajah tempat baru (hidden gems)',
    'Belanja/thrifting',
    'Menonton konser/festival musik',
    'Menonton pertunjukan seni/teater',
    'Berkunjung ke museum/galeri seni',
    'Mengikuti workshop/kelas kreatif',
    'Astrologi/tarot',
    'Mengoleksi tanaman unik',
    'Aquascaping/merawat ikan hias',
    'Melakukan DIY (Do It Yourself) project',
    'Lainnya (isi sendiri)',
];
