export const INDUSTRY_CATEGORIES = [
    'Jasa',
    'F&B - Resto/Depot',
    'Hotel & Villa',
    'Kesenian, Hiburan dan Rekreasi',
    'Perdagangan Besar/Eceran',
    'Konsultan',
    'Informasi & Komunikasi',
    'Kesehatan',
    'Event Organizer',
    'Konstruksi - Interior',
    'F&B - Coffee Shop',
    'Konstruksi - Exterior',
    'Pendidikan',
    'Arsitektur',
    'Agen Perjalanan',
    'Real Estate',
    'F&B - Supplier',
    'Keuangan & Akuntansi',
    'F&B - Baking',
    'Elektronik',
    'Penyewaan & Sewa Guna',
    'Asuransi',
    'Lain-Lain',
    'Elektrikal',
    'Otomotif - Roda Empat',
    'Sosial',
    'Otomotif - Parts & Aksesoris',
    'Ketenagakerjaan',
    'Trader Forex/Saham',
    'Percetakan',
    'Otomotif - Roda Dua & Tiga',
    'Pemerintahan',
    'Pergudangan',
    'Perpajakan',
    'Valuta Asing',
    'Perikanan',
    'Pertanian',
    'Salon',
    'Sekuritas',
    'Ahli Ilmiah & Teknis',
    'Farmasi',
    'Gas & Uap',
    'Pengolahan',
    'Badan Internasional',
    'Kehutanan',
    'Pengangkutan',
    'Pertambangan & Penggalian',
    'Reparasi',
];

export const HOBBY_LIST = [
    'Nonton Film',
    'Ngopi',
    'Mendengar Musik',
    'Bulutangkis',
    'Seminar Bisnis',
    'Art & Craft',
    'Camping/Glamping',
    'Running/Jogging',
    'Fitness/Weightlifting',
    'BBQ',
    'Persekutuan Doa',
    'Motorcycle Riding',
    'Nyanyi',
    'Pekerjaan Sosial',
    'Bermain Musik',
    'Memasak',
    'Baking',
    'Hiking',
    'Membaca',
    'Photography',
    'Yoga',
    'Gadget/Elektronik',
    'Basketball',
    'Sepeda',
    'Meditasi',
    'Graphic Design',
    'Parenting',
    'Bertaman',
    'Gaming',
    'Billiard',
    'Melukis',
    'Soccer/Futsal',
    'Merangkai Bunga',
    'Pilates',
    'Tennis Meja',
    'Wine Tasting',
    'Dancing',
    'Tennis',
    'Makeup/Cosmetic',
    'Rafting',
    'Golf',
    'Catur',
    'Martial Art',
    'Memancing',
    'Nutrisi',
    'Horse Riding',
    'Scuba Diving',
    'Ice Skating',
    'Hair Styling',
    'Surfing',
    'Ikan Hias',
    'Menjahit',
    'Kaligrafi',
    'Kayaking',
    'Origami',
    'Reptil',
    'Lainnya (Isi Sendiri)',
];
